### ISSUE TITLE
Apply n-layer arquitecture

### ISSUE THREAD

**Issue by drielnox** [mtadese/CIS#1]
It would be good, be applied to the solution, necessary to facilitate the maintenance of the code and separate sub-layers of the system itself.

**Comment by mtadese** [comment]
Thank you Drielnox. Is there any other addon/code you'd suggest I add to this? Please see additional codes and screenshots as well. Cheers.

**Comment by drielnox** [comment]
@mtadese, thanks for answering. I mention that if you have never made an application in layers suggest that for these applications, you implement the architectural pattern MVP (Model-View-Presenter). Alsogives rise to can apply agile methodologies for software development such as test-driven development.
This pattern is very common for Windows Forms applications.
On YouTube there are tutorials that explain clearly and easily this architectural pattern.
I can leave you this link so you dig deeper more on the subject:
- https://www.youtube.com/watch?v=GVYd6-LfQm4&list=PLI4_Dhk0WbIRHLfOu31N0npWVML0pm7GZ

If you want me to help with the implementation, would need the source code is accessible and not in the form of compressed file.

**Comment by mtadese** [comment]
Hi @drielnox Just to let you know, I've uploaded the source code files for this application to my page. Please check out anytime for your review:
https://github.com/mtadese/CIS/tree/master/cis_sourcecode
Thanks.

**Comment by drielnox** [comment]
@mtadese, thank for upload the source code. I'm gonna practice TDD with this and do some change in the code.

I forget says... i need the script to create the database and test data for this.

**Comment by mtadese** [comment]
Hi @drielnox, apologies for the delay in my feedback. I've uploaded the database scripts and you can view them on this page: https://github.com/mtadese/CIS/tree/master/his_record_mysql for further review or update. Thanks.

**Comment by drielnox** [comment]
@mtadese, is there any possibility that you can add me as a contributor to the repository?

**Comment by mtadese** [comment]
Hi @drielnox, I've just added you as a collaborator to this repository as requested. Thanks.

**Comment by mtadese** [comment]
Hi @drielnox, a quick update please - I just did a cleanup on my github portal and re-committed all my files hence your update to this repo (https://github.com/mtadese/CIS) was cleaned up in the process. If its fine with you, can you please re-commit your updates anytime you can?

I wouldn't be doing any more cleanup on that repo henceforth. Thanks.

**Comment by drielnox** [comment]
@mtadese, I just saw that they were not the changes it had made a few days ago and I worry about it. Now I know you did a cleanup, I'm more relaxed.

In these days I'm going to commit all the changes I made. There will be changes that will leave recorded in the Issue Tracker.
