### ISSUE TITLE
Use ConnectionString via Properties of Project instead hardcoded connection string.

### ISSUE THREAD

**Issue by drielnox** [mtadese/CIS#2]
I see in various part of code, the connection string to connect to database is hardcoded.
This is a defect of the code and if in a future is need to be changed its necessary to be changed in all places that this string is.
To solve this problem use Connection String Properties of Properties of Project. It's the most easy way to keep this part of code clean.

**Comment by mtadese** [comment]
@drielnox thanks for all your feedback, really appreciated. I actually designed this app back in 2013 when I first learned the C# language (.NET 3.5) and also having a lot of exposure to clinical info system  processes (which I still do). I designed it for practical purpose then and recently published it for public use or amending for the public's preferred use.

I'd be glad to send you full application which I uploaded here or even upload it's modules into a separate folder here on github. 

I presently work with ASP.NET 4.0 and have designed a usable web version of the same clinical app (using web forms and MySql database). Will be glad to share this too eventually. Thanks.
